import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless:true, ...(process.env.BROWSER_CHANNEL ? {channel:process.env.BROWSER_CHANNEL} : {}) });
const context = await browser.newContext({ viewport:{width:1440,height:1000} });
const page = await context.newPage(), errors = [], external = [], checks = [];
const output = fileURLToPath(new URL('../../tmp/selective-review-qa/', import.meta.url));
await mkdir(output,{recursive:true});
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('request', request => { if (/^https?:/.test(request.url())) external.push(request.url()); });
const click = action => page.locator(`[data-action="${action}"]`).click();
const focused = selector => page.locator(selector).evaluate(node => document.activeElement === node);
const changeScenario = value => page.locator('#scenario').selectOption(value);
const technical = async () => JSON.parse(await page.locator('.preview pre').textContent());
const noOverflow = async () => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
const shot = async name => { await page.evaluate(() => scrollTo(0,0)); await page.screenshot({path:path.join(output,`${name}.png`),fullPage:true}); };
try {
  await page.goto(new URL('index.html',import.meta.url).href);
  await page.keyboard.press('Tab'); assert.ok(await focused('.skip'));
  await page.keyboard.press('Enter'); assert.ok(await focused('#main'));
  await click('execute');
  assert.ok(await page.locator('#stage-error').isVisible());
  assert.ok(await focused('[name="direction"][value="text-first"]'));
  assert.equal(await page.locator('[name="direction"]').first().getAttribute('aria-invalid'),'true');
  await page.keyboard.press('Space'); await page.keyboard.press('ArrowRight');
  assert.ok(await focused('[name="direction"][value="product-first"]'));
  await page.locator('[name="tone"][value="reject"]').check();
  await page.locator('#tone-form button').click();
  await click('explore');
  let data = await technical();
  assert.equal(data.inference.action,'reject');
  assert.equal(data.confirmedCopy,'Hecho despacio.');
  await noOverflow(); await shot('desktop-normal');
  checks.push('Skip link, required-direction error, native radio arrows and focus restoration work; optional rejection preserves confirmed copy.');

  await click('execute');
  assert.match(await page.locator('.status').innerText(),/Ejecución revisada/);
  assert.ok(await page.locator('[data-action="publish"]').isDisabled());
  await page.locator('#render-reviewed').check();
  assert.ok(await focused('#render-reviewed'));
  await click('publish'); assert.match(await page.locator('.status').innerText(),/Publicación revisada/);
  await click('edit-copy');
  assert.ok(await focused('#copy-text'));
  await page.keyboard.press('Escape'); assert.ok(await focused('[data-action="edit-copy"]'));
  await click('edit-copy');
  await page.locator('#copy-form button[type="submit"]').click();
  assert.ok(await page.locator('#copy-error').isVisible()); assert.ok(await focused('#copy-note'));
  await page.locator('#copy-text').fill('Una pieza para tu pausa.');
  await page.locator('#copy-note').fill('Corrección ficticia del titular.');
  await page.locator('#copy-form button[type="submit"]').click();
  assert.ok(await focused('[data-action="edit-copy"]'));
  assert.equal(await page.locator('[name="direction"]:checked').count(),0);
  assert.match(await page.locator('.status').innerText(),/Exploración/);
  assert.ok(await page.locator('[data-action="publish"]').isDisabled());
  assert.ok(await page.locator('[name="tone"][value="reject"]').isChecked());
  data = await technical(); assert.equal(data.confirmedCopy,'Una pieza para tu pausa.');
  await page.locator('#history > summary').click();
  assert.match(await page.locator('#history').innerText(),/conservadas, sin vigencia/);
  checks.push('Execution, render and publication are separate; correction dialog validates a reason, restores focus and preserves unrelated decisions/old approvals.');

  await changeScenario('collaborator'); await click('explore');
  data = await technical(); assert.equal(data.assetUse,'placeholder-only');
  assert.match(data.attribution,/Otro autor/);
  await click('reference');
  assert.ok(await page.locator('[data-issue="asset"]').isVisible());
  await click('asset');
  data = await technical(); assert.equal(data.assetUse,'authorized-demo-original');
  checks.push('Unapproved collaborator image is not a reusable original or an identity rule; excluded reference needs a distinct authorized replacement.');

  await changeScenario('incomplete'); await click('explore');
  assert.equal((await technical()).missingFacts,true);
  assert.equal((await technical()).assetUse,'placeholder-only');
  assert.ok(await page.locator('[data-issue="facts"]').isVisible());
  await changeScenario('low-resolution');
  assert.ok(await page.locator('[data-issue="resolution"]').isVisible());
  await click('resolution');
  assert.equal(await page.locator('[data-issue="resolution"]').count(),0);
  await changeScenario('missing-site'); await click('explore');
  assert.equal((await technical()).siteAccess,false);
  await click('site'); assert.equal((await technical()).siteAccess,true);
  await changeScenario('channel-conflict'); await click('explore');
  assert.ok(await page.locator('[data-issue="channel"]').isVisible());
  assert.equal((await technical()).rule.scope,'website');
  await click('channel'); assert.equal(await page.locator('[data-issue="channel"]').count(),0);
  await changeScenario('channel-conflict'); await page.locator('#task').selectOption('instagram-story');
  assert.equal(await page.locator('[data-issue="channel"]').count(),0);
  checks.push('Incomplete facts, low resolution, site access and channel conflicts surface task-specific consequences without demanding every inference.');

  await changeScenario('normal');
  await page.locator('[name="tone"][value="accept-proposal"]').check(); await page.locator('#tone-form button').click();
  await page.locator('[name="direction"][value="text-first"]').check(); await click('execute');
  await page.locator('#sources > summary').click();
  await page.locator('#source-tools > summary').click(); await click('source-changed');
  assert.ok(await page.locator('[data-issue="source"]').isVisible());
  assert.ok(await page.locator('#sources').evaluate(node => node.open));
  assert.ok(await focused('[data-action="source-changed"]'));
  assert.ok(await page.locator('[name="tone"][value="accept-proposal"]').isChecked());
  await page.locator('#task').selectOption('website-change');
  for (const id of ['action','fit','alt','site']) assert.ok(await page.locator(`[data-issue="${id}"]`).isVisible());
  await page.locator('#proposal-text').fill(''); await page.locator('#proposal-form button[type="submit"]').click();
  assert.ok(await focused('#proposal-text')); assert.ok(await page.locator('#proposal-error').isVisible());
  await page.locator('#proposal-text').fill('<script>window.injected = true</script>'); await page.locator('#proposal-form button[type="submit"]').click();
  assert.equal(await page.evaluate(() => window.injected),undefined);
  assert.ok(await page.locator('[name="tone"][value="accept-proposal"]').isChecked());
  checks.push('Changed source/task revokes dependent review but preserves preferences and source disclosure; edited text is escaped and errors are linked.');

  await page.setViewportSize({width:390,height:844});
  for (const name of ['normal','incomplete','collaborator','low-resolution','missing-site','channel-conflict']) {
    await changeScenario(name); await noOverflow();
    if (['normal','incomplete','channel-conflict'].includes(name)) await shot(`mobile-${name}`);
  }
  await click('edit-copy'); await noOverflow(); await shot('mobile-correction'); await page.keyboard.press('Escape');
  await page.setViewportSize({width:320,height:740});
  for (const name of ['normal','incomplete','channel-conflict']) { await changeScenario(name); await noOverflow(); }
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('#task').focus();
  assert.equal(await page.locator('#task').evaluate(node => getComputedStyle(node).outlineWidth),'3px');
  assert.equal(await page.locator('#task').evaluate(node => getComputedStyle(node).transitionDuration),'0s');
  assert.equal(await page.evaluate(() => localStorage.length),0);
  assert.deepEqual(errors,[]); assert.deepEqual(external,[]);
  checks.push('390/320px layouts, correction dialog, focus and reduced motion checked; no browser errors, HTTP(S) traffic or persisted state.');
  const result = {status:'pass',checks,errors,external};
  await writeFile(path.join(output,'verification.json'),JSON.stringify(result,null,2),'utf8');
  console.log(JSON.stringify(result,null,2));
} finally { await browser.close(); }
