// Report interface text is local; model calls only translate existing source prose.
export const REPORT_COPY = {
  es: {
    locale: 'es-AR', title: 'lectura de marca', wordmark: 'Lectura de marca / Instagram', jump: 'Ir a la revisión ↓',
    draft: 'Borrador basado en evidencia', subtitle: 'Lo que el perfil muestra. Lo que podemos inferir. Lo que todavía necesita tu mirada.',
    inferenceCount: (n) => `${n} ${n === 1 ? 'inferencia' : 'inferencias'}`,
    reviewCount: (n) => `${n} ${n === 1 ? 'punto' : 'puntos'} a revisar`,
    sample: (n) => `Muestra ${n} de publicaciones propias revisadas`, gallery: 'Muestras del perfil revisadas',
    topics: ['Paleta percibida', 'Uso del color', 'Tipografía', 'Fotografía', 'Materialidad', 'Composición', 'Tono de voz', 'Llamados a la acción', 'Personalidad', 'Orientación para UI'],
    status: { inferred: 'Inferencia', 'needs-review': 'Revisar', verified: 'Verificado' },
    confidence: { high: 'alta', medium: 'media', low: 'baja' },
    confidenceLabel: 'Confianza', confidencePending: 'Confianza pendiente', noSource: 'Sin fuente suficiente',
    unknown: 'Todavía no hay una regla defendible.', sources: 'Fuentes', noColor: 'Sin propuesta',
    noColorReason: 'No hay una propuesta vigente sustentada por gráficos propios revisados.', approximate: 'aproximado',
    primary: 'Principal', secondary: 'Secundario', kind: { image: 'Imagen revisada', text: 'Texto propio', metadata: 'Perfil', manual: 'Nota manual' },
    start: '01 / Punto de partida', observed: 'Lo observado', noBio: 'El perfil no tiene biografía disponible.',
    observedNote: 'La biografía y las imágenes son datos del perfil capturado. Las propuestas de identidad que siguen son interpretaciones, no instrucciones oficiales de la marca.',
    profileLink: 'Ver perfil original ↗', imageStat: 'imágenes propias revisadas y usadas', captionStat: 'textos propios considerados',
    excludedStat: 'imágenes sin revisar, fuera del análisis', pendingStat: 'temas que requieren decisión humana',
    identity: '02 / Lectura de identidad', interpreted: 'Lo interpretado',
    identityNote: 'Cada tema muestra su estado, la razón y las fuentes concretas. “Inferencia” significa hipótesis sustentada; todavía no equivale a una regla aprobada.',
    samples: '03 / Muestras aproximadas', color: 'Color candidato',
    colorNote: 'Los códigos se estiman desde gráficos propios revisados. Confirman una dirección para conversar, no especificaciones finales ni colores extraídos de productos.',
    origin: '04 / Rastro de origen', sourceHeading: 'Fuentes consultables',
    sourceNote: 'Los enlaces de cada inferencia te traen aquí. Las miniaturas están integradas en este HTML para poder revisarlo sin conexión y sin abrir archivos aparte.',
    original: 'Texto original de la fuente', translation: 'Traducción al inglés del borrador. Los textos originales se conservan en las fuentes.',
    decision: '05 / Decisión humana', review: 'Qué revisar antes de diseñar',
    steps: ['Confirmá qué inferencias representan a la marca hoy.', 'Corregí o descartá las reglas que las fuentes no sostienen.', 'Definí colores exactos, tipografía de interfaz y decisiones UI con la persona responsable de la marca.'],
    footer: (date) => `Generado desde una captura pública de Instagram y una revisión local de evidencia. El análisis es un borrador con fecha ${date}; las publicaciones pueden haber cambiado desde la captura. Este archivo contiene copias reducidas de imágenes del perfil y debe compartirse sólo con permiso de sus titulares.`,
  },
  en: {
    locale: 'en-US', title: 'brand review', wordmark: 'Brand review / Instagram', jump: 'Go to review ↓',
    draft: 'Evidence-based draft', subtitle: 'What the profile shows. What we can infer. What still needs your review.',
    inferenceCount: (n) => `${n} ${n === 1 ? 'inference' : 'inferences'}`,
    reviewCount: (n) => `${n} ${n === 1 ? 'item' : 'items'} to review`,
    sample: (n) => `Sample ${n} from reviewed profile-owned posts`, gallery: 'Reviewed profile samples',
    topics: ['Perceived palette', 'Color roles', 'Typography', 'Photography', 'Materials and texture', 'Composition', 'Tone of voice', 'Calls to action', 'Personality', 'UI direction'],
    status: { inferred: 'Inferred', 'needs-review': 'Review needed', verified: 'Verified' },
    confidence: { high: 'high', medium: 'medium', low: 'low' },
    confidenceLabel: 'Confidence', confidencePending: 'Confidence not assessed', noSource: 'Insufficient evidence',
    unknown: 'There is not enough evidence for a defensible rule yet.', sources: 'Sources', noColor: 'No proposal',
    noColorReason: 'No current proposal is supported by reviewed profile-owned graphics.', approximate: 'approximate',
    primary: 'Primary', secondary: 'Secondary', kind: { image: 'Reviewed image', text: 'Profile-owned text', metadata: 'Profile', manual: 'Manual note' },
    start: '01 / Starting point', observed: 'What we observed', noBio: 'No profile biography is available.',
    observedNote: 'The biography and images come from the captured profile. The identity proposals below are interpretations that need the brand owner’s approval.',
    profileLink: 'View original profile ↗', imageStat: 'reviewed profile-owned images used', captionStat: 'profile-owned captions considered',
    excludedStat: 'unreviewed images excluded from analysis', pendingStat: 'topics requiring a human decision',
    identity: '02 / Reading the identity', interpreted: 'What we inferred',
    identityNote: 'Each topic shows its status, rationale and sources. “Inferred” means a supported hypothesis that still needs approval as a brand rule.',
    samples: '03 / Approximate samples', color: 'Candidate colors',
    colorNote: 'Color codes are estimated from reviewed profile-owned graphics. They provide a direction for discussion; they are provisional and are not extracted from product photos.',
    origin: '04 / Evidence trail', sourceHeading: 'Sources you can inspect',
    sourceNote: 'Each inference links here. Thumbnails are embedded in this HTML so you can review it offline. English source summaries are translations; expand an entry to inspect its original text.',
    original: 'Original source text', translation: 'English translation of the draft. Original source text remains available in the evidence entries.',
    decision: '05 / Human decision', review: 'What to review before designing',
    steps: ['Confirm which inferences represent the brand today.', 'Correct or discard rules that the sources do not support.', 'Agree on exact colors, interface typography and UI decisions with the person responsible for the brand.'],
    footer: (date) => `Generated from a public Instagram snapshot and locally reviewed evidence. This analysis is a draft dated ${date}; posts may have changed since capture. This file contains reduced copies of profile images and should only be shared with their owners’ permission.`,
  },
};

export function reportCopy(language) {
  if (!Object.hasOwn(REPORT_COPY, language)) throw new Error('Report language must be es or en.');
  return REPORT_COPY[language];
}
