import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, mkdtemp, writeFile, readFile, readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { _electron } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const packaged = process.argv.includes('--packaged');
const output = path.join(root, 'tmp', 'app-shell-qa');
await mkdir(output, { recursive: true });
const profile = await mkdtemp(path.join(output, 'chromium-'));
const testTemp = realpathSync.native(tmpdir());
const source = await mkdtemp(path.join(testTemp, 'synthetic-import-'));
const backup = await mkdtemp(path.join(testTemp, 'synthetic-backup-'));
await writeFile(path.join(source, 'instagram-source.json'), '{"username":"example.studio","biography":"Fictional test fixture."}');
const exe = packaged ? path.join(root, 'dist', 'app', 'win-unpacked', 'Instagram to OpenDesign.exe') : require('electron');
const args = [...(packaged ? [] : [root]), `--shell-test-data=${profile}`, '--shell-test-hidden'];
// No Node path or provider key is available to the packaged application.
const env = Object.fromEntries(['SystemRoot', 'WINDIR', 'TEMP', 'TMP', 'COMSPEC', 'USERPROFILE', 'APPDATA', 'LOCALAPPDATA'].filter(key => process.env[key]).map(key => [key, process.env[key]]));
env.PATH = path.join(process.env.SystemRoot, 'System32');
const results = [];
let electronApp;
async function poll(operation, expected, timeout = 15000) {
  const end = Date.now() + timeout;
  let result;
  do { result = await operation(); if (expected(result)) return result; await new Promise(resolve => setTimeout(resolve, 100)); } while (Date.now() < end);
  throw new Error(`Condition timed out: ${JSON.stringify(result)}`);
}
async function workerPid() {
  return electronApp.evaluate(({ app }) => app.getAppMetrics().find(item => item.name === 'Local shell check')?.pid);
}
try {
  electronApp = await _electron.launch({ executablePath: exe, args, env, timeout: 30000 });
  let page = await electronApp.firstWindow();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('#start').waitFor();
  await poll(() => page.evaluate(() => window.appShell.status()), value => value.state?.status === 'idle');
  assert.deepEqual(await page.evaluate(() => [typeof require, typeof process]), ['undefined', 'undefined']);
  const prefs = await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());
  assert.equal(prefs.sandbox, true); assert.equal(prefs.contextIsolation, true); assert.equal(prefs.nodeIntegration, false);
  // Dialog substitution lives in this test process, never in production IPC or preload.
  await electronApp.evaluate(({ dialog }, selected) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [selected] });
    dialog.showMessageBox = async () => ({ response: 1 });
  }, source);
  await page.locator('#new-project').click();
  await page.locator('#project-name').fill('Example studio');
  await page.locator('#project-url').fill('https://example.invalid/profile');
  await page.locator('#save-project').click();
  await page.locator('#project-error').waitFor({ state: 'visible' });
  assert.equal(await page.evaluate(() => document.activeElement.id), 'project-url');
  await page.locator('#project-url').fill('https://www.instagram.com/example.studio/');
  await page.locator('#save-project').click();
  await page.locator('#project-dialog').waitFor({ state: 'hidden' });
  await page.locator('#import-project').click();
  await page.locator('#project-dialog').waitFor({ state: 'visible' });
  await page.locator('#project-name').fill('Imported fixture');
  await page.locator('#save-project').click();
  await page.locator('#project-dialog').waitFor({ state: 'hidden' });
  const imported = (await page.evaluate(() => window.localWorkspace.list())).workspace.projects.find(item => item.name === 'Imported fixture');
  assert.ok(imported);
  const copiedSource = path.join(profile, 'workspace', 'projects', imported.id, 'data', 'imported', 'instagram-source.json');
  assert.deepEqual(await readFile(copiedSource), await readFile(path.join(source, 'instagram-source.json')));
  await electronApp.evaluate(({ dialog }, selected) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [selected] }); }, backup);
  assert.equal((await page.evaluate(id => window.localWorkspace.exportBackup(id), imported.id)).ok, true);
  assert.equal((await readdir(backup)).length, 1);
  assert.equal((await page.evaluate(id => window.localWorkspace.trash(id), imported.id)).ok, true);
  assert.equal((await page.evaluate(id => window.localWorkspace.restore(id), imported.id)).ok, true);
  assert.equal((await page.evaluate(id => window.localWorkspace.open(id), imported.id)).ok, true);
  const jobProof = await electronApp.evaluate(async ({ app }, projectId) => {
    const path = process.getBuiltinModule('path'), fs = process.getBuiltinModule('fs');
    const packagedRequire = process.getBuiltinModule('module').createRequire(path.join(app.getAppPath(), 'package.json'));
    const { Workspace } = packagedRequire('./desktop/workspace.cjs');
    const { JobStore, digest } = packagedRequire('./desktop/jobs.cjs');
    const crypto = process.getBuiltinModule('crypto');
    const workspace = new Workspace(path.join(app.getPath('userData'), 'workspace'));
    const root = path.join(app.getPath('userData'), 'sqlite-proof');
    const options = { resolveProject: id => workspace.project(id) };
    let store = new JobStore(root, options);
    try {
      const job = store.createJob(projectId, { taskId: crypto.randomUUID(), operation: 'report', provider: 'fake', model: 'synthetic', configRevision: digest('synthetic-config'), taskRevision: 1 });
      await store.dispatch(job.id, store.authorize(job.id, job.planHash), () => ({ remoteId: 'synthetic-no-network' }));
      const output = store.complete(job.id, null, payload => fs.writeFileSync(path.join(payload, 'result.txt'), 'Synthetic SQLite packaging proof'), () => true);
      const sqlite = store.db.prepare('SELECT sqlite_version() AS version').get().version;
      store.close(); store = new JobStore(root, options);
      return { version: sqlite, state: store.view(job.id).state, outputRetained: store.view(job.id).output === output.output };
    } finally { store.close(); }
  }, imported.id);
  assert.equal(jobProof.state, 'completed'); assert.equal(jobProof.outputRetained, true);
  results.push(`Bundled node:sqlite ${jobProof.version}: intent/acknowledgement, inventoried snapshot and fresh-store recovery without external Node or network`);
  const syntheticKey = `synthetic-${randomUUID()}`;
  await page.locator('#settings').click();
  await page.locator('#credential-key').fill(syntheticKey);
  await page.locator('#save-credential').click();
  await poll(() => page.locator('#credential-state').textContent(), value => value?.includes('Clave guardada'));
  assert.equal(await page.locator('#credential-key').inputValue(), '');
  assert.equal(JSON.stringify(await page.evaluate(() => window.localWorkspace.credentialStatus())).includes(syntheticKey), false);
  const protectedFile = path.join(profile, 'workspace', 'credentials', 'apify.json');
  assert.equal((await readFile(protectedFile, 'utf8')).includes(syntheticKey), false);
  assert.equal(await electronApp.evaluate(async ({ safeStorage }, value) => {
    const plain = await safeStorage.decryptStringAsync(Buffer.from(value.encrypted, 'base64'));
    return plain.result === value.expected;
  }, { encrypted: JSON.parse(await readFile(protectedFile, 'utf8')).encrypted, expected: syntheticKey }), true);
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
  await page.keyboard.press('Escape');
  await poll(() => page.evaluate(() => document.activeElement.id), value => value === 'settings');
  await electronApp.evaluate(({ safeStorage }) => {
    const original = safeStorage.isAsyncEncryptionAvailable.bind(safeStorage);
    safeStorage.isAsyncEncryptionAvailable = async () => { safeStorage.isAsyncEncryptionAvailable = original; return false; };
  });
  await page.locator('#settings').click();
  await poll(() => page.locator('#save-credential').isDisabled(), value => value === true);
  assert.equal(await page.locator('#credential-key').isDisabled(), true);
  assert.equal(await page.locator('#remove-credential').isEnabled(), true);
  await page.keyboard.press('Escape');
  results.push('Managed create/import/open/backup/trash/restore, source byte equality, real Windows DPAPI and cleared password input');
  await page.evaluate(() => document.querySelector('.skip').click());
  assert.equal((await page.evaluate(() => window.appShell.status())).ok, true);
  await page.locator('#start').focus();
  const focus = await page.locator('#start').evaluate(el => getComputedStyle(el).outlineStyle);
  assert.notEqual(focus, 'none');
  await page.keyboard.press('Enter');
  await poll(() => page.evaluate(() => window.appShell.status()), value => value.state?.ticks >= 1);
  const pid = await workerPid(); assert.ok(pid);
  const before = (await page.evaluate(() => window.appShell.status())).state.ticks;
  assert.equal((await page.evaluate(() => window.appShell.startCheck())).ok, false);
  await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].close());
  await page.locator('#close-dialog').waitFor({ state: 'visible' });
  assert.equal(await page.evaluate(() => document.activeElement.id), 'keep-open');
  await page.keyboard.press('Escape');
  await page.locator('#close-dialog').waitFor({ state: 'hidden' });
  await poll(() => page.evaluate(() => document.activeElement.id), value => value === 'exit');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'exit');
  await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].close());
  await page.locator('#confirm-close').click();
  await poll(() => electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), value => value === 0);
  await new Promise(resolve => setTimeout(resolve, 1100));
  assert.equal(await workerPid(), pid);
  const newWindow = electronApp.waitForEvent('window');
  const second = spawn(exe, args, { env, windowsHide: true, stdio: 'ignore' });
  await new Promise((resolve, reject) => { second.once('error', reject); second.once('exit', code => code === 0 ? resolve() : reject(new Error(`Second instance exited ${code}`))); });
  page = await newWindow;
  await page.waitForLoadState();
  const resumed = await page.evaluate(() => window.appShell.status());
  assert.ok(resumed.state.ticks > before); assert.equal(await workerPid(), pid);
  assert.equal(await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  results.push('Packaged core/sharp, isolated renderer, keyboard close dialog and background worker/second instance');
  await page.evaluate(() => scrollTo(0, 0));
  const screenshot = await electronApp.evaluate(async ({ BrowserWindow }) => {
    const image = await BrowserWindow.getAllWindows()[0].webContents.capturePage(undefined, { stayHidden: true });
    return image.toPNG().toString('base64');
  });
  await writeFile(path.join(output, packaged ? 'packaged.png' : 'development.png'), Buffer.from(screenshot, 'base64'));
  // Renderer failure is independent of utility process ownership.
  await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.forcefullyCrashRenderer());
  assert.equal(await workerPid(), pid);
  await poll(() => electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), value => value === 0);
  const reopened = electronApp.waitForEvent('window');
  await electronApp.evaluate(({ Menu }) => Menu.getApplicationMenu().items[0].submenu.items[0].click());
  page = await reopened; await page.waitForLoadState();
  await poll(() => page.evaluate(() => window.appShell.status()), value => value.state?.status === 'completed');
  assert.equal(await workerPid(), pid);
  results.push('Renderer crash, menu reopen and observed completion retain the same worker');
  await page.setViewportSize({ width: 360, height: 650 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.emulateMedia({ forcedColors: 'active', reducedMotion: 'reduce' });
  await page.locator('#start').focus();
  assert.notEqual(await page.locator('#start').evaluate(el => getComputedStyle(el).outlineStyle), 'none');
  const current = page.url();
  await page.evaluate(() => { location.href = 'https://example.invalid/'; });
  await new Promise(resolve => setTimeout(resolve, 200));
  assert.equal(page.url(), current);
  assert.equal(await page.evaluate(() => window.open('https://example.invalid/') === null), true);
  const networkDenied = await page.evaluate(async () => { try { await fetch('https://example.invalid/'); return false; } catch { return true; } });
  assert.equal(networkDenied, true);
  assert.deepEqual(errors, []);
  results.push('External navigation, popup, fetch blocked; narrow layout and high contrast focus');
  const closed = electronApp.waitForEvent('close');
  await page.evaluate(() => window.appShell.exit());
  await closed;
  // OS process lookup must show that explicit Exit terminated the utility worker.
  assert.throws(() => process.kill(pid, 0));
  results.push('Explicit Exit terminates the worker');
  electronApp = await _electron.launch({ executablePath: exe, args, env, timeout: 30000 });
  page = await electronApp.firstWindow();
  await poll(() => page.evaluate(() => window.localWorkspace?.list()), value => value?.workspace?.projects.length === 2);
  assert.equal((await page.evaluate(() => window.localWorkspace.credentialStatus())).credentials.providers.apify, true);
  assert.equal((await page.evaluate(id => window.localWorkspace.open(id), imported.id)).ok, true);
  assert.equal((await page.evaluate(() => window.localWorkspace.removeCredential('apify'))).credentials.providers.apify, false);
  const reopenedExit = electronApp.waitForEvent('close'); await page.evaluate(() => window.appShell.exit()); await reopenedExit;
  results.push('Fresh app launch retains projects and protected credential configuration; explicit key removal');
  await writeFile(path.join(output, packaged ? 'packaged-verification.json' : 'development-verification.json'), JSON.stringify({ packaged, results }, null, 2));
  console.log(JSON.stringify({ packaged, passed: results }, null, 2));
} finally {
  if (electronApp) await electronApp.close().catch(() => {});
}
